[2022-09-24 16:07:19,844] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: xcom_dag.get_testing_increase_data scheduled__2022-09-24T16:06:05.615135+00:00 [queued]>
[2022-09-24 16:07:19,862] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: xcom_dag.get_testing_increase_data scheduled__2022-09-24T16:06:05.615135+00:00 [queued]>
[2022-09-24 16:07:19,863] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-24 16:07:19,863] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-09-24 16:07:19,863] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-24 16:07:19,882] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_testing_increase_data> on 2022-09-24 16:06:05.615135+00:00
[2022-09-24 16:07:19,886] {standard_task_runner.py:52} INFO - Started process 220 to run task
[2022-09-24 16:07:19,891] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 'get_testing_increase_data', 'scheduled__2022-09-24T16:06:05.615135+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp08r3hy6e', '--error-file', '/tmp/tmp3it_mv5v']
[2022-09-24 16:07:19,892] {standard_task_runner.py:77} INFO - Job 10: Subtask get_testing_increase_data
[2022-09-24 16:07:19,990] {logging_mixin.py:109} INFO - Running <TaskInstance: xcom_dag.get_testing_increase_data scheduled__2022-09-24T16:06:05.615135+00:00 [running]> on host 0ff875464cf0
[2022-09-24 16:07:20,087] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=get_testing_increase_data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-24T16:06:05.615135+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-24T16:06:05.615135+00:00
[2022-09-24 16:07:20,954] {api.py:356} INFO - ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
[2022-09-24 16:07:20,956] {api.py:367} INFO - ascii should target any language(s) of ['Latin Based']
[2022-09-24 16:07:20,963] {api.py:385} INFO - We detected language [('English', 1.0), ('Dutch', 1.0), ('Indonesian', 1.0)] using ascii
[2022-09-24 16:07:20,964] {api.py:419} INFO - ascii is most likely the one. Stopping the process.
[2022-09-24 16:07:20,964] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 15, in get_testing_increase
    testing_increase = json.loads(res.text)['totalTestResultsIncrease']
KeyError: 'totalTestResultsIncrease'
[2022-09-24 16:07:20,989] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=xcom_dag, task_id=get_testing_increase_data, execution_date=20220924T160605, start_date=20220924T160719, end_date=20220924T160720
[2022-09-24 16:07:21,012] {standard_task_runner.py:92} ERROR - Failed to execute job 10 for task get_testing_increase_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 15, in get_testing_increase
    testing_increase = json.loads(res.text)['totalTestResultsIncrease']
KeyError: 'totalTestResultsIncrease'
[2022-09-24 16:07:21,027] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-24 16:07:21,116] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
